config/routes.rb
Rails.application.routes.draw do
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  root 'simple_pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>aidan_app</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="navbar-brand" id="aidansPortfolio">
            <a href="#">Bike Berlin</a>
          </div>
        </div> <!-- /navbar header -->
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right" id="nav">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", simple_pages_about_path %></li>
            <li><%= link_to "Contact", simple_pages_contact_path %></li>
          </ul>
        </div> <!-- /nav -->
      </div> <!-- /nav container -->
    </nav> <!-- /navigation bar -->

    <%= yield %>

    <div class="buffer"></div> <!-- footer buffer-->

    <footer>
      <div class="container">
        <p class="text-muted">&copy; 2018 Bike Berlin</p>
      </div>
    </footer>
  </body>
</html>

app/views/simple_pages/about.html.erb
<h1>About Bike Berlin</h1>
<p>Welcome to the Bike Berlin official website! We are a used bike dealer located in Berlin, Germany. We look forward to helping you with all of your bike-related needs!</p>

app/views/simple_pages/contact.html.erb
<h1>Contact</h1>
<p>Berlin Bikes is located at 1 Berlinerstraße, Berlin. <br>
   You can reach us by telephone at 049 123 456 7890.</p>

app/views/simple_pages/index.html.erb
<h1>Welcome to Bike Berlin</h1>
<h2>Your source for used bikes in Berlin</h2>

<%= image_tag("bike.jpg", class: "img-responsive") %>